kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
    name: mysql-ingress
    namespace: jpetstore
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
    ingressClassName: nginx
    tls:
    - hosts:
      - 'aditya.netwincbs.in'
      secretName: netwincbs-tls
    rules:
    - host: 'aditya.netwincbs.in'
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jpetstore
              port:
                number: 80
